### ISSUE TITLE
Do you plan to update this addon for 9.1?

### ISSUE THREAD

**Issue by claybarrett** [kristoffer-tvera/wow-addon-conduit-drop-location#1]

**Comment by Inzagio** [comment]
Yes

**Comment by Inzagio** [comment]
@claybarrett  Sorry for the delay, we have started work in a 9.1 branch that will be merged in as soon as possible.

**Comment by Extraversi0n** [comment]
Can I help with anything? I could update droplocations for hunters and demon hunters if that is okay :)

**Comment by Inzagio** [comment]
New release slated for release today. If all goes well it should be on curse in a an hour or two.
@Watermelon-EU @claybarrett
